name: Hexo自动部署
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx hexo clean && npx hexo generate
      - name: 部署Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./public